---
- name: Include private variables
  ansible.builtin.include_vars: private.yml
  tags: 
    - smb
    - gnucash
    - vscode

- name: Import smb tasks
  ansible.builtin.import_tasks: 01_smb.yml
  tags: smb

- name: Import gnucash tasks
  ansible.builtin.import_tasks: 02_gnucash.yml
  tags: gnucash

- name: Import vscode tasks
  ansible.builtin.import_tasks: 03_vscode.yml
  tags: vscode